
class oxts:

    lat = []    # latitude of the oxts - unit(deg)
    lon = []    # longitude of the oxts-unit (deg)
    alt = []    # altitude of the oxts-unit (m)
    roll = []   # roll angle (rad),    0 = level, positive = left side up,      range: -pi   .. +pi
    pitch = []  # pitch angle (rad),   0 = level, positive = front down,        range: -pi/2 .. +pi/2
    yaw = []    # heading (rad),       0 = east,  positive = counter clockwise, range: -pi   .. +pi
    vn = []     # velocity towards north (m/s)
    ve = []     # velocity towards east (m/s)
    vf = []     # forward velocity, i.e. parallel to earth-surface (m/s)
    vl = []     # leftward velocity, i.e. parallel to earth-surface (m/s)
    vu = []     # upward velocity, i.e. perpendicular to earth-surface (m/s)
    ax = []     # acceleration in x, i.e. in direction of vehicle front (m/s^2)
    ay = []     # acceleration in x, i.e. in direction of vehicle left  (m/s^2)
    az = []     # acceleration in x, i.e. in direction of vehicle top  (m/s^2)
    af = []     # forward acceleration (m/s^2)
    al = []     # leftward  acceleration (m/s^2)
    au = []     # upward  acceleration (m/s^2)
    wx = []     # angular rate around x (rad/s)
    wy = []     # angular rate around y (rad/s)
    wz = []     # angular rate around z (rad/s)
    wf = []     # angular rate around forward axis (rad/s)
    wl = []     # angular rate around leftward  axis (rad/s)
    wu = []     # angular rate around upward  axis (rad/s)
    pos_accuracy = []     # velocity accuracy (north/east in m)
    vel_accuracy = []     # velocity accuracy (north/east in m/s)
    navstat = []     # navigation status (see navstat_to_string)
    numsats = []     # number of satellites tracked by primary GPS receiver
    posmode = []     # position mode of primary GPS receiver (see gps_mode_to_string)
    velmode = []     # velocity mode of primary GPS receiver (see gps_mode_to_string)
    orimode = []     # orientation mode of primary GPS receiver (see gps_mode_to_string)


    def get_value(self, ll):
        self.lat.append((ll[0]))
        self.lon.append(ll[1])
        self.alt.append(ll[2])
        self.roll.append((ll[3]))
        self.pitch.append((ll[4]))
        self.yaw.append((ll[5]))
        self.vn.append((ll[6]))
        self.ve.append((ll[7]))
        self.vf.append((ll[8]))
        self.vl.append((ll[9]))
        self.vu.append((ll[10]))
        self.ax.append((ll[11]))
        self.ay.append((ll[12]))
        self.az.append((ll[13]))
        self.af.append((ll[14]))
        self.al.append((ll[15]))
        self.au.append((ll[16]))
        self.wx.append((ll[17]))
        self.wy.append((ll[18]))
        self.wz.append((ll[19]))
        self.wf.append((ll[20]))
        self.wl.append((ll[21]))
        self.wu.append((ll[22]))
        self.pos_accuracy.append(ll[23])
        self.vel_accuracy.append(ll[24])
        self.navstat.append(ll[25])
        self.numsats.append(ll[26])
        self.posmode.append(ll[27])
        self.velmode.append(ll[28])
        self.orimode.append(ll[29])

